### ISSUE TITLE
Unable to execute code action on nightly

### ISSUE THREAD

**Issue by xanderio** [weilbith/nvim-code-action-menu#10]
When i try to execute any code action by pressing `<CR>` i get pressended with this error message

neovim version: v0.6.0-dev+364-gec4731d98

```
E5108: Error executing lua ...me/xanderio/Local/share/nvim/runtime/lua/vim/lsp/buf.lua:605: command: expected string, got nil
stack traceback:
        ...me/xanderio/Local/share/nvim/runtime/lua/vim/lsp/buf.lua:605: in function 'execute_command'
        ...enu/lua/code_action_menu/lsp_objects/actions/command.lua:43: in function 'execute'
        ...acker/opt/nvim-code-action-menu/lua/code_action_menu.lua:107: in function 'execute_selected_action'
        [string ":lua"]:1: in main chunk
```

**Comment by weilbith** [comment]
Interesting. I just checked the PR list and also the git blame for the `vim.lsp.buf` module. Nothing has changed. And the code just passes the action from the server to this function (i.e. [this data](https://microsoft.github.io/language-server-protocol/specification.html#command)). So either your server returns something awkward, or I interpreted this wrongly as a command and it is rather an [CodeAction](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#codeAction) object. The decision what it is, is made [here](https://github.com/weilbith/nvim-code-action-menu/blob/4efac33349a6d4669c2072a22ede61d94886c48d/lua/code_action_menu/shared_utils.lua#L46).
I'm very sorry, but could you maybe add some logging of the raw server data above the line I just linked and post me the output?

**Comment by weilbith** [comment]
Any maybe verify that you can execute the action just by using `:lua vim.lsp.buf.code_action()` and selecting the same action.

**Comment by weilbith** [comment]
I might can easily fix that by switching the if-else statement and check for all mandatory fields a `Command` must have and else it is a `CodeAction`. Actually a `CodeAction` either has an `edit` or a `command` attribute. But both are optional for this `or`. If your server for a reason I don't understand here sends you a `CodeAction` without any of those two, I assume it is a `Command` straight. This assumtion might be wrong.
But in that case the execution of the `CodeAction` would fail [here](https://github.com/weilbith/nvim-code-action-menu/blob/4efac33349a6d4669c2072a22ede61d94886c48d/lua/code_action_menu/lsp_objects/actions/code_action.lua#L79). I need to double check how the native menu does this...

**Comment by xanderio** [comment]
It works perfectly with `:lua vim.lsp.buf.code_action()`. Maybe i should have mentioned that i'm working with rust-analyzer.

I'm was just about to add the debug code you mentioned, but your ever fast with your replies and i'm not sure if you still nedd this information :)

**Comment by weilbith** [comment]
The [native implementation](https://github.com/neovim/neovim/blob/ec4731d982031e363a59efd4566fc72234bb43c8/runtime/lua/vim/lsp/buf.lua#L477) does actually nothing different.

**Comment by weilbith** [comment]
Oh

**Comment by weilbith** [comment]
> It works perfectly with `:lua vim.lsp.buf.code_action()`. Maybe i should have mentioned that i'm working with rust-analyzer.
> 
> I'm was just about to add the debug code you mentioned, but your ever fast with your replies and i'm not sure if you still nedd this information :)

Oh... I'm confused.

**Comment by weilbith** [comment]
Haha, I use rust-analyzer as well. But I barely see commands form it, just code actions of type quickfixed or refactoring. But I'm not too much of a Rust developer unfortunately.

**Comment by weilbith** [comment]
Could you please still add the logging?

**Comment by xanderio** [comment]
I added a `print(vim.inspect(data))` before the if statment on line 46.

```
{
  data = {
    codeActionParams = {
      context = {
        diagnostics = {}
      },
      range = {
        end = {
          character = 14,
          line = 1
        },
        start = {
          character = 14,
          line = 1
        }
      },
      textDocument = {
        uri = "file:///usr/home/xanderio/Projects/testy/src/main.rs"
      }
    },
    id = "make_raw_string:RefactorRewrite:0"
  },
  kind = "refactor.rewrite",
  title = "Rewrite as raw string"
}
```

**Comment by xanderio** [comment]
I should properly also mention that im currently using the lastest `master` of rust-analyzer.

**Comment by weilbith** [comment]
Aaaaah. This is an action that needs to be resolved. It uses the `data` field. Nice. This is why I wanted to have feedback. I never had this and somehow I forgot/missed that this exists.

**Comment by weilbith** [comment]
Alright, let's see how fast I can fix this.

**Comment by weilbith** [comment]
It would be helpful if I could have local setup where I can trigger your case. Is this `testy` project public? The cursor position I can see.

**Comment by weilbith** [comment]
Else I think I have a straight forward solution which should just work. I would open a PR and you can test it.

**Comment by xanderio** [comment]
In a way :D 

Just create it with `cargo new testy` :D

**Comment by xanderio** [comment]
> Else I think I have a straight forward solution which should just work. I would open a PR and you can test it.

Sure

**Comment by weilbith** [comment]
Btw: this was really just added last night. So you really found a up to date bug.

**Comment by weilbith** [comment]
So if I got this right, NeoVim now sets this capability that it can resolve code actions and then rust analyzer sends such actions only. This is why it worked before where the capability was not there and rust analyzer was sending "normal" actions.

**Comment by xanderio** [comment]
Finding these kinds of bugs is exactly the reason why I always run the lasted version of software. Some one has to spot and report them :D 

Also thanks for the plugin and the very quick responce

**Comment by weilbith** [comment]
> Finding these kinds of bugs is exactly the reason why I always run the lasted version of software. Some one has to spot and report them :D

That is generous 😅 
I do it to have the most recent cool features. But I'm not yet on last nights build 🙈 

I'm glad that I can help.

---

I also just realized that NeoVim introduced custom commands. I need to handle this as well. 🤯

**Comment by weilbith** [comment]
@xanderio may I ask were you take the nightly from? I was using the ArchLinux package `nvim-nightly-bin` but that doesn't work anymore as apparently NeoVim doesn't upload nightlies to the downloads anymore.
I have a solution, and it also makes the parsing more stable. So it will resolve actions, but also if it can't resolve it or failed to parse what the server send (which basically means it send crap or I'm not on the most recent specification version), it will warn the user with notifications, but still continue with the rest of the actions.

**Comment by weilbith** [comment]
As I currently can't update NeoVim @xanderio would you please give #11 a try and check if it works for you? Thanks!

**Comment by xanderio** [comment]
> @xanderio may I ask were you take the nightly from? 

I just build them from directly from source. 

> would you please give #11 a try

With that patch applied i get this error message when executing `:CodeActionMenu`
```
E5108: Error executing lua ...m-code-action-menu/lua/code_action_menu/shared_utils.lua:55: attempt to index loc
al 'data' (a nil value)
```

**Comment by weilbith** [comment]
Ah sure, that makes sense. Stupid mistake. I hate not strongly typed languages. They make me crazy. 😑 
I'll get the nightly myself to not abuse you as a tester. Its too asynchronous with too much delay anyway. I'll ping you in the PR once I think it should really work.
