### ISSUE TITLE
Support <C-n> and <C-p> for navigating list

### ISSUE THREAD

**Issue by DevonMorris** [weilbith/nvim-code-action-menu#12]
Basically I want to use <C-n> and <C-p> for navigating the list of options. Is this possible or can it be supported?

**Comment by weilbith** [comment]
That is easy to do. Somewhere in your setup create a file `after/ftplugin/code-action-menu-menu.vim` (or `.lua`) and there map your keys to up and down. 
Tell if you have issues to implement it.

**Comment by DevonMorris** [comment]
Ahh super easy, thanks.
Just throw that
```
nnoremap <C-n> j
nnoremap <C-p> k
```
In that file. Thanks!

**Comment by weilbith** [comment]
Perfect 👌🏾
