### ISSUE TITLE
codeaction menu break "solid" border highlight

### ISSUE THREAD

**Issue by etrnal70** [weilbith/nvim-code-action-menu#14]
After triggering codeaction, using floating window with "solid" border show different highlight

https://user-images.githubusercontent.com/5826834/135575479-158fb46b-fbda-4b4f-a5b0-5a6171c8b983.mp4

**Comment by weilbith** [comment]
Hmm, that is not nice.
The only place I customize the floating border highlight group is [here](https://github.com/weilbith/nvim-code-action-menu/blob/4efac33349a6d4669c2072a22ede61d94886c48d/ftplugin/code-action-menu-warning-message.vim#L4). But it actually uses a `set winhighlight`. And as this is within a filetypep plugin for the warning message buffer, this should be actually fine. Not good. I hate NeoVim its handling of window options. It's a nightmare. Already that I must use this user auto command is a proof of it.

Could you please try to comment out this whole auto command group and see if it remains fine?

**Comment by etrnal70** [comment]
Uncommenting the augroup fix the problem here

**Comment by weilbith** [comment]
Okay, so I need to find out how to do these window options properly. Especially for the highlights. I actually wanted to allow the user to customize the highlights individually, but it is just a nightmare. Maybe that works then too.
Would you say its the best solution for the moment just to remove the special border highlight for the warning message to fix it?

**Comment by etrnal70** [comment]
Personally i would just remove it for now. That highlight is not a major dealbreaker though

**Comment by weilbith** [comment]
@etrnal70 I should have fixed the issue by removing this special highlight for the moment. Please re-open the issue if you could still have trouble with it.
I'll see how I can bring back this feature with a proper implementation soon.

**Comment by etrnal70** [comment]
Many thanks !
