### ISSUE TITLE
opening menu messes with vertical split

### ISSUE THREAD

**Issue by xanderio** [weilbith/nvim-code-action-menu#23]
When opening the code action menu while having a vertical split. The active windows gets set to a width of 82 characters.

**Comment by xanderio** [comment]
No it is wider then the window.

I attached a screenshot below:
![grafik](https://user-images.githubusercontent.com/6298052/137503072-7d87cab8-e076-481e-a670-123e491336cb.png)

**Comment by weilbith** [comment]
Btw you are observing an issue with the `rust-analyzer` atm which split changes in the same line into multiple edits/diffs. Unfortunately my diff algorithm isn't handling it correctly yet. I'm sorry for that. Need to find time to completely rework this part of the plugin. 😑

**Comment by xanderio** [comment]
Works perfectly! Thanks for the quick fix
