### ISSUE TITLE
Errors when code action creates a new file

### ISSUE THREAD

**Issue by Gelio** [weilbith/nvim-code-action-menu#30]
When using nvim-jdtls when seeing a command that that creates a new class/interface/enum:
![image](https://user-images.githubusercontent.com/889383/141281033-7492c6e0-79a0-47c1-bdec-633d0ca2156c.png)

there are errors in the console coming from this plugin:

![image](https://user-images.githubusercontent.com/889383/141281082-fc7fbad2-c1bd-4f1b-9710-1f2e8a7fc2c9.png)

```
Error detected while processing CursorMoved Autocommands for "<buffer=211>":
E5108: Error executing lua ...ode_action_menu/lsp_objects/edits/text_document_edit.lua:82: attempt to index local 'first_original_complete_
line' (a nil value)
stack traceback:
        ...ode_action_menu/lsp_objects/edits/text_document_edit.lua:82: in function 'get_list_of_added_lines_in_edit'
        ...ode_action_menu/lsp_objects/edits/text_document_edit.lua:227: in function 'get_diff_lines'
        ...action-menu/lua/code_action_menu/windows/diff_window.lua:35: in function 'get_diff_lines_formatted'
        ...action-menu/lua/code_action_menu/windows/diff_window.lua:115: in function 'get_content'
        ...action-menu/lua/code_action_menu/windows/base_window.lua:30: in function 'update_buffer_content'
        ...action-menu/lua/code_action_menu/windows/base_window.lua:68: in function 'open'
        ...acker/opt/nvim-code-action-menu/lua/code_action_menu.lua:98: in function 'update_diff_window'
        ...acker/opt/nvim-code-action-menu/lua/code_action_menu.lua:105: in function 'update_selected_action'
        [string ":lua"]:1: in main chunk
```

Looks like the failing bit is 
https://github.com/weilbith/nvim-code-action-menu/blob/32a02caf1cb6d5d31167945a2df9d371d68b1009/lua/code_action_menu/lsp_objects/edits/text_document_edit.lua#L78-L82

I suspect it is because it wants to create a new file that is not yet loaded, so `vim.lsp.util.get_line` returns `nil`. I added `print(vim.inspect(self.edits))` in

https://github.com/weilbith/nvim-code-action-menu/blob/32a02caf1cb6d5d31167945a2df9d371d68b1009/lua/code_action_menu/lsp_objects/edits/text_document_edit.lua#L164

and the results are:

```
{ {
    newText = "package org.eclipse.sirius.web.graphql.datafetchers.mutation;\n\npublic class CreateUnitCallInput {\n\n}\n",
    range = {
      end = {
        character = 0,
        line = 0
      },
      start = {
        character = 0,
        line = 0
      }
    }
  } }
```

Keep in mind I already had the fix from https://github.com/weilbith/nvim-code-action-menu/pull/29 applied. Otherwise, this problem never surfaced before, because the error from https://github.com/weilbith/nvim-code-action-menu/pull/29 was reported first

**Comment by weilbith** [comment]
I love your extensive description of the issue and the amount of work you have already invested into identifying the source of the issue. I highly appreciate it. 🙏🏾 

I just opened a draft PR which hopefully fixes this issue. As I still haven't completed my local work with unit tests, this still requires a manual test. You could either try this your self with your existing example from this issue or help me to reproduce this myself. Though I for sure could do the latter with try-error, I think it would be best you try it yourself because then we have the perfect proof that this change fixed the bug you saw before.

**Comment by Gelio** [comment]
Thanks for kind words and a very quick fix! It is indeed spot-on - there are no more errors when browsing through code actions that would create a new file


https://user-images.githubusercontent.com/889383/141829962-bdd1db38-4c4c-432e-8bf1-81c8137bcaae.mp4

From my side, https://github.com/weilbith/nvim-code-action-menu/pull/31 solves the problem

**Comment by weilbith** [comment]
Amazing. Thanks for testing the PR so quickly. 🙏🏾
