### ISSUE TITLE
Not all code actions are detected

### ISSUE THREAD

**Issue by Gelio** [weilbith/nvim-code-action-menu#4]
Hey!

The plugin looks great and I've tried using it but it looks like it does not detect code actions that I care about. This is the one thing that prevents me from switching to it.

I have tried using it with tsserver, null-ls, and stylelint_lsp configured in lspconfig, and it only detected code actions from stylelint_lsp.

Built-in `vim.lsp.buf.code_action()`:

![image](https://user-images.githubusercontent.com/889383/135140789-8a89619a-94e6-4d3f-a861-23f988f02895.png)

Telescope's `:Telescope code_actions` also works well:
![image](https://user-images.githubusercontent.com/889383/135140965-361eca57-4189-43b7-90b8-2066b788f42a.png)

Plugin (only `stylelint_lsp` code actions are detected):
![image](https://user-images.githubusercontent.com/889383/135140893-df9c19b0-ed32-4501-be48-d2a22770bac7.png)

I'm afraid the built-in `vim.lsp.buf.code_aciton()` is using different logs than the plugins uses.

Built-in:

https://github.com/neovim/neovim/blob/3507d58dfb87923aa4031cbefaf1ef576a45dcaf/runtime/lua/vim/lsp/buf.lua#L456-L489

Plugin:
https://github.com/weilbith/nvim-code-action-menu/blob/0fea23ef716546ed1491d9d27d1c58ba658c2e01/lua/code_action_menu/shared_utils.lua#L35-L39

Do you think it would be possible to show all the code actions in the popup instead of only some of them?

**Comment by Gelio** [comment]
I added
```lua
print(vim.inspect(all_responses))
print(vim.inspect(all_actions))
```


to the `request_servers_for_actions` function and this is what I'm getting:

![image](https://user-images.githubusercontent.com/889383/135141879-c643a3c1-55d7-416e-b5c6-147f5a2ba998.png)

There is clearly a code actions from tsserver, but somehow that's not propagated to `all_actions` (the bottom log is an empty table)

**Comment by Gelio** [comment]
I thought it might be https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils interfering, but I disabled it and there still are no results

**Comment by Gelio** [comment]
I think I got it, a PR incoming

**Comment by weilbith** [comment]
Thank you very much for this detailed report. You are absolutely right, we must show all server responses. Happy that you already checked that the request function works alright. Let's see what the issue is with the parsing.

**Comment by weilbith** [comment]
Ah you solved it. Amazing. Thank you very much. Appreciate it a lot! 🙏🏾

**Comment by Gelio** [comment]
No problem! https://github.com/weilbith/nvim-code-action-menu/pull/5 looks to solve my problems
