### ISSUE TITLE
How to change border?

### ISSUE THREAD

**Issue by AndOrangutan** [weilbith/nvim-code-action-menu#46]
I was just wondering if there was a way to change the “single” border to something else.

![image](https://user-images.githubusercontent.com/40435989/158324111-3dd78623-9d2d-47ce-a3bf-f711618f8605.png)

**Comment by weilbith** [comment]
Unfortunately this is hard-coded right now. I was planning to make such things configurable but then I was in the situation that I need to rewrite the whole plugin. Something I haven't finished till today.
It isn't to hard to make a quick patch for this issue. Would you like me to do so?

**Comment by AndOrangutan** [comment]
That would be cool, but no pressure. Really liking the plugin by the way. :D

**Comment by AndOrangutan** [comment]
Works wonderfully, thank you so much.

**Comment by matthiasbeyer** [comment]
What did you set the value to, to remove the border? `none` does not work for me.
