### ISSUE TITLE
Option to hide action kind names

### ISSUE THREAD

**Issue by arafatamim** [weilbith/nvim-code-action-menu#54]
Is there an option to hide the action kinds in parentheses (as highlighted below)?
![image](https://user-images.githubusercontent.com/31634638/172579588-6fff25d3-ff3d-4a06-b812-7a5f30ab4e29.png)

**Comment by DasOhmoff** [comment]
I want this too :)

**Comment by weilbith** [comment]
Would you like do open a PR for this? 🙂
