### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by DanielBarton446** [weilbith/nvim-code-action-menu#7]
Hello, I am fairly new to this kind of stuff, and I was running into an issue as follows when invoking:
``` :CodeActionMenu ```

"E5105: Error while calling lua chink: ...lua/code_action_menu/lsp_objects/actions/base_action.lua:8 attempt to call field 'validate' ( a nil value)"

-- I searched this up just in google and foun out in another repo, a similar error. The repo then mentioned the requirement to have nvim nightly, or nvim version > .50

As such, I was wondering if the same was true for here. 

Thanks!

**Comment by weilbith** [comment]
Yes, I'm sorry the docs need to be improved here. I'll add this. The plugin needs `>0.5.0`. Thanks for pointing that out.

**Comment by weilbith** [comment]
I prepared a PR to extend the docs for this. Do you have any other issue with the requirements that need to be added? Or does it work now for you?
